version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./dissco:/app/dissco
    environment:
      - DJANGO_SETTINGS_MODULE=dissco.settings.local
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=dissco
      - POSTGRES_USER=dissco
      - POSTGRES_PASSWORD=dissco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: 