# Generated by Django 4.0.4 on 2022-05-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('code', models.TextField(blank=True, max_length=255)),
                ('wikidata_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
