# Generated by Django 4.0.4 on 2022-06-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_institutionuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='wikidata_id',
            new_name='ror_id',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='code',
        ),
    ]
