# Generated by Django 4.0.4 on 2022-07-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='responder',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name_owner'),
        ),
    ]
