# Generated by Django 4.0.4 on 2022-07-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maturity', '0002_responder_unique_name_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity.category')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity.responder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('responder', 'category'), name='unique_maturity_response'),
        ),
    ]
