# Generated by Django 4.0.4 on 2022-04-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.IntegerField()),
                ('scope', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('value_type', models.TextField()),
                ('policy_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policyarea')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubcategoryPolicyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('rules', models.TextField()),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.servicesubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyComponentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('policy_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policycomponent')),
                ('service_subcategory_policy_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.servicesubcategorypolicycomponent')),
            ],
        ),
        migrations.AddField(
            model_name='policycomponent',
            name='service_subcategory_policy_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.servicesubcategorypolicycomponent'),
        ),
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('policy_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policyarea')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionPolicyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.institution')),
                ('policy_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policycomponent')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionPolicyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_exists', models.BooleanField()),
                ('owner', models.TextField()),
                ('signatory', models.TextField()),
                ('documentation_exists', models.BooleanField()),
                ('documentation_next_review_date', models.DateTimeField()),
                ('documentation_language', models.CharField(max_length=2)),
                ('documentation_public', models.BooleanField()),
                ('documentation_shareable', models.BooleanField()),
                ('documentation_provided', models.BooleanField()),
                ('documentation_details', models.TextField()),
                ('policy_summary', models.TextField()),
                ('additional_notes', models.TextField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.institution')),
                ('policy_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policyarea')),
            ],
        ),
    ]
