# Generated by Django 4.0.4 on 2022-06-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policycomponent',
            name='type',
            field=models.TextField(choices=[('bool', 'Bool'), ('number', 'Number'), ('option', 'Option Single'), ('options', 'Option Multiple')]),
        ),
    ]
