# Generated by Django 4.0.4 on 2022-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_alter_institutionpolicyarea_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycomponent',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
