# Generated by Django 4.0.4 on 2022-07-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_policycomponent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
