# Generated by Django 4.0.4 on 2022-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_service_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepolicymapping',
            name='allowed_options',
            field=models.ManyToManyField(to='policy.policycomponentoption'),
        ),
        migrations.AddField(
            model_name='servicepolicymapping',
            name='allowed_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepolicymapping',
            name='rule',
            field=models.TextField(choices=[('equal', 'Equal'), ('or', 'Or')], default='or'),
            preserve_default=False,
        ),
    ]
