# Generated by Django 4.0.4 on 2022-07-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_servicepolicymapping_allowed_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycomponentoption',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
