# Generated by Django 4.0.4 on 2022-07-25 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_wikidata_id_institution_ror_id_and_more'),
        ('policy', '0007_policycomponentoption_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.institution')),
                ('policy_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policyarea')),
            ],
        ),
        migrations.AddConstraint(
            model_name='institutionresponse',
            constraint=models.UniqueConstraint(fields=('institution', 'policy_area'), name='unique_policy_response'),
        ),
    ]
