# Generated by Django 4.0.4 on 2022-07-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_institutionresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionpolicyarea',
            name='documentation_provided',
        ),
        migrations.AddField(
            model_name='institutionpolicyarea',
            name='name',
            field=models.TextField(default='policy'),
            preserve_default=False,
        ),
    ]
